version: '3.9'
services:
  vibe-llm:
    build: .
    image: vibe-llm:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./:/app
    restart: unless-stopped
